### ISSUE TITLE
关于缓存数据的时效性

### ISSUE THREAD

**Issue by wuyang1314** [BaiCanLin/BCNetwork#1]
哥们，你的这个做得挺好的，非常好用。但我想到信息有时候会改变，即使同一个网址。这个怎么处理，如果使用你的库

**Comment by chunfengsun** [comment]
可以手动指定清楚某一接口的缓存吗？

**Comment by BaiCanLin** [comment]
@chunfengsun 可以的，你稍微改一下源码就行了

**Comment by BaiCanLin** [comment]
@wuyang1314 可以的，你看一下源码，我更新了
